fix: remove unnecessary properties panel padding
bpmn-io/properties-panel pull request #145
Opened 2022-04-06 10:14 UTC by Skaiir

Related to https://github.com/camunda/camunda-modeler/issues/2831.

The negative margin is there to 'hide' the last group's separator when a scrollbar is visible.

This avoids that:

 This has the side effect of moving the scrollbar itself down a little. Not really visible, and definitely a little weird but

2022-04-06 12:21 UTC, andreasgeier commented
@Skaiir pls provide an artifact for design review.

2022-04-06 12:46 UTC, barmac requested changes
Check out the comment.

2022-04-08 07:14 UTC, Skaiir commented
@andreasgeier We're going to first remove the padding from the props panel, and then add the margin inside of the modeler when I integrate the new version. So we'll defer design review to a little later if that sounds correct to you.

2022-04-08 07:33 UTC, barmac approved these changes

2022-04-08 07:33 UTC, merged