feat: add optgroup option for select
bpmn-io/properties-panel pull request #204
Opened 2022-12-24 15:22 UTC by etozhealkhipce

This PR adds `optgroup` props to the `Select.js` component.

You going to be able to use this by adding `getGroups` function returns an array with objects with `key` and `label` fields in the select component props, also you going to need to add `groupKey` field which has to equal `key` field in the group which you want to bind this option in your option object.

Example:

```
function ExampleComponent(props) {
  const { element } = props

  const getGroups = (element) => {
    return [
      {
        key: 'first',
        label: 'first test group'
      },
      {
        key: 'second',
        label: 'second test group'
      }
    ]
  }

  const getOptions = (element) => {
    return [
      {
        groupKey: 'first',
        label: 'Test option 1',
        value: 'test1'
      },
      {
        groupKey: 'first',
        label: 'Test option 2',
        value: 'test2',
        disabled: true
      },
      {
        groupKey: 'second',
        label: 'Test option 3',
        value: 'test3'
      },
      {
        label: 'Test option 4 without group',
        value: 'test4'
      }
    ]
  }

  return [
    SelectEntry({
      element,
      id: 'test',
      getGroups,
      label: translate('test'),
      getValue: () => null,
      setValue: (value) => console.log(value),
      getOptions
    })
  ]
}
```

Closes https://github.com/bpmn-io/properties-panel/issues/169

2022-12-24 15:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bpmn-io/properties-panel?pullRequest=204) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bpmn-io/properties-panel?pullRequest=204) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bpmn-io/properties-panel?pullRequest=204) it.</sub>

2023-02-08 08:40 UTC, barmac commented
@etozhealkhipce We need you to sign the CLA if you want your contribution to be merged.

2023-02-08 17:31 UTC, etozhealkhipce commented
> 

Ok, how can I do that?

2023-02-08 17:37 UTC, etozhealkhipce commented
> @etozhealkhipce We need you to sign the CLA if you want your contribution to be merged.

Ok, I signed it.

2023-02-10 07:55 UTC, barmac commented
Cool, thanks.

I am not convinced about the proposed API. We require implementors to keep getGroups and getOptions in sync while the data structure could enforce it. Imagine if we keep `getOptions` as the only available method:

```javascript
const getOptions = (element) => {
  return [
    {
      label: 'first',
      children: [
        {
          label: 'Test option 1',
          value: 'test1'
        },
        {
          label: 'Test option 2',
          value: 'test2',
          disabled: true
        },
      ]
    },
    {
      label: 'second',
      children: [
        {
          label: 'Test option 3',
          value: 'test3'
        },
      ]
    },
    {
      label: 'Test option 4 without group',
      value: 'test4'
    }
  ]
}
```

So no need to care about `groupKey`, and as a bonus the ordering of options is explicit.

2023-02-10 07:55 UTC, barmac requested changes
See the comment above.

2023-02-12 07:59 UTC, etozhealkhipce commented
> See the comment above.

I changed API according to your comment.

Please, check the changes.

2023-02-13 08:28 UTC, barmac commented
Great, thank you!

2023-02-13 10:26 UTC, merged