feat(textarea): provide auto-resizeable textarea
bpmn-io/properties-panel pull request #214
Opened 2023-02-02 15:59 UTC by smbea

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/705, specifically https://github.com/bpmn-io/bpmn-js-properties-panel/pull/864#discussion_r1094405640

![capture o3BxBW_optimized](https://user-images.githubusercontent.com/58601/216551070-a2350d43-c29c-46cf-a3ff-4de9b2f17f2a.gif)

https://github.com/bpmn-io/bpmn-js-properties-panel/pull/864 pins this version of `properties-panel` and allows to test end-to-end

2023-02-02 16:57 UTC, nikku requested changes
Great start I think. 

Usability wise I'm not sold on the `max-height` usage and the behavior it triggers: As a user I want to resize the panel to the contents. `max-height` prevents me to manually resize:

![capture l4evWU_optimized](https://user-images.githubusercontent.com/58601/216387076-8aa14dbd-07b5-4def-85ba-942615d8e2fb.gif)

Instead I'd ensure that we assert the maximum height until which we _autoresize_ via JavaScript, not CSS. :arrow_right: Users can still resize on top.

I'd like to make sure that the scroll bar, if possible is hidden. This can be accomplished by making the panel 2px larger than the scroll height, I believe.

Both can be seen in action here:

![capture WZnbpf_optimized](https://user-images.githubusercontent.com/58601/216390442-8f6e786a-b472-4fbe-b8f8-3e239d446237.gif)

Last I'd assume that a reasonable default high is assumed on initial render. If I display multi-line text then we should apply the same auto-resize rules on initial rendering, or the result is unexpected:

![capture 5Bcdfh_optimized](https://user-images.githubusercontent.com/58601/216390863-a9b35068-fb08-496f-92ab-bef4f896eff4.gif)

2023-02-02 16:58 UTC, nikku commented
Pushed https://github.com/bpmn-io/properties-panel/pull/214/commits/5ec10920741ed6ca85420b2b9128998fd479ac8f to address the first two issues mentioned [here](https://github.com/bpmn-io/properties-panel/pull/214#pullrequestreview-1281474171). 

Remaining: Auto-resize on initial render.

2023-02-02 18:04 UTC, nikku commented
Fixed via https://github.com/bpmn-io/properties-panel/pull/214/commits/019bd8fb33ee00049bb4939fed1ae973082879c4. 

![capture Djge9E_optimized](https://user-images.githubusercontent.com/58601/216406558-5d1d8ace-8d3c-426b-b7aa-dbb488d656e1.gif)

2023-02-02 19:41 UTC, nikku reviewed
Good stuff :clap:

2023-02-02 19:41 UTC, nikku approved these changes

2023-02-03 07:59 UTC, merged

2023-02-03 08:36 UTC, marstamm commented on test/spec/components/TextArea.spec.js
> +GEHTS
👋 🌏

2023-02-03 08:40 UTC, philippfromme commented on test/spec/components/TextArea.spec.js
> +GEHTS
Geht so.

2023-02-03 08:43 UTC, nikku commented on test/spec/components/TextArea.spec.js
> +GEHTS
:smile: