#311 removed sorting from ListGroup component
bpmn-io/properties-panel pull request #353
Opened 2024-04-26 07:42 UTC by AlexanderSkrock

This pull request aims to fix #311 . Currently, it is being developed.

- [ ] Remove "shouldSort" property
- [ ] Warn if this property is still used
- [ ] Adjust testcases
- [ ] Discover dependant components in potentially other projects. This includes to remove the flag and if sorting is necessary to reimplement the sorting on this level.

2024-04-26 11:43 UTC, nikku commented
@AlexanderSkrock Great to see you picking this up. You should be able to link both projects, this core + bpmn-js-properties-panel to test them together:

```
cd bpmn-js-properties-panel
npm link ../properties-panel

...
```

2024-04-26 21:04 UTC, AlexanderSkrock commented
Regarding necessary changes in the project `bpmn-js-properties-panel`, I saw the following.

**Camunda 7**
Usages without the `shouldSort` flags, thus using the previous default of sorting:
- FieldInjectionGroup
- InMappingGroup
- OutMappingGroup
- ExecutionListenerGroup
- TaskListenerGroup
- ConnectorInputGroup
- ConnectorOutputGroup
- ExtensionPropertiesGroup

Usages with the `shouldSort` flag set to `false`, thus already disabling sorting:
- ErrorsGroup
- FormDataGroup
- InputGroup
- OutputGroup
- ProcessVariablesGroup
- ExtensionPropertiesGroup

**Camunda 8**
Usages with the `shouldSort` flag set to `false`, thus already disabling sorting:
- ExtensionPropertiesGroup
- HeaderGroup
- InputGroup
- OutputGroup

**Changes to be made**
For all usages that already set the `shouldSort` flag set to `false`, we can simply remove the flag. For any other usage I will need to evalute the necessity of sorting.

2024-04-29 07:49 UTC, AlexanderSkrock commented
This pull request together with changes made in [#1047 in bpmn-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1047) should be good to go now, from my point of view.

One more question, I saw that we released `properties-panel` version 3.18.2 already, so we would need to increate to 3.18.2 and also update it for `bpmn-js-properties-panel`. Is this a step which is done automatically during the release process?

2024-04-29 08:39 UTC, nikku commented
Once you did it then I can give it my review.

2024-04-29 08:59 UTC, AlexanderSkrock commented
> @AlexanderSkrock You'd want to rebase this PR on main before merge.

I checked once again, but it seems my commits were based on main's head already.

2024-05-02 08:09 UTC, nikku commented
Will look into your changes today. Thanks already for your work :clap:

2024-05-06 13:38 UTC, nikku commented
After some distractions I hope I find the time to finalize my review + testing tomorrow.

2024-05-06 15:39 UTC, nikku commented
I found the time to review the change, along with https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1047.

A few notes:

* From what it looks to me the change is incomplete. Looking at sorting at the core [`List#compareFn`](https://github.com/bpmn-io/properties-panel/blob/1b2cbec8e55bfb470695bde2a302e60110a65261/src/components/entries/List.js#L54) is used along with sorting to implement sort features; without sorting there is no necessity for `compareFn`, we want to ditch it which I sketched in https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1047/commits/d883a0fcc3cb19ddf422b1ab3a86bc1595cfb28a.
* Integration testing https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1047 I found a bunch of places where auto focus is now broken; we want to ensure that items are added last to the list (no magic), and focused regardless, sketched for `Execution Listeners > Execution Listener > Field injections` via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1047/commits/99535149a0297c369372666cda6895f1411707f2). Without that change in the relevant places we see the following interaction, shown on the example of `User Task (Generated Form): Form Fields > Field > Properties`:
  
  ![capture nSTWvz_optimized](https://github.com/bpmn-io/properties-panel/assets/58601/3b055aa0-442e-4b42-ae1a-c2925cf11940)

Other than that the solution feels solid, improves C7, and does not break C8 functionality (where we do not sort already :tm:). Good job!

2024-05-06 15:40 UTC, nikku requested changes
Consider to ditch `List#compareFn`, cf. https://github.com/bpmn-io/properties-panel/pull/353#issuecomment-2096326398.

2024-05-28 08:33 UTC, nikku approved these changes

2024-05-28 08:33 UTC, nikku commented
Waiting for CI to pass before we go ahead and merge this.

2024-05-28 08:45 UTC, nikku commented on CHANGELOG.md
> +* `FIX`: removed sorting for list grops ([#353](https://github.com/bpmn-io/properties-panel/pull/353))
```suggestion
* `FEAT`: do not sort list items alphabetically ([#311](https://github.com/bpmn-io/properties-panel/issues/311) 
* `CHORE`: remove sorting for list groups ([#353](https://github.com/bpmn-io/properties-panel/pull/353))
```

2024-05-28 08:49 UTC, merged